version: "3"

services:
  db:
    container_name: bori-db-container
    image: lauvsong/bori-db:210815
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=boridb
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul

  front:
    container_name: front-container
    image: dhslrl321/boribob-l7:frontend
    ports:
      - "5000:5000"

  back:
    container_name: back-container
    image: dhslrl321/boribob-l7:back
    ports:
      - "8080:8080"
    environment:
      - "spring.datasource.url=jdbc:mysql://bori-db-container/bob_l7?characterEncoding=utf8?serverTimezone=Asia/Seoul
    depends_on:
      - db

  proxy:
    image: dhslrl321/boribob-l7:proxy
    ports:
      - "80:80"
    depends_on:
      - front
      - back
